### ISSUE TITLE
SampleDistributor disproportionately allocates samples.

### ISSUE THREAD

**Issue by jvasilakes** [MiniEggz/EffiARA#1]
The issue is on lines [213-214](https://github.com/MiniEggz/EffiARA/blob/7534a54fb4981ffbbdd52f7c7568702d61ed2d49/src/effiara/preparation.py#L213-L214) where it seems the number of annotators is hard-coded to 6. When the number of annotators is different from this, some annotators will be assigned disproportionately more samples to annotate when double_proportion > 0.

### Fix

The lines 

```python
link_1_annotator = f"user_{(i+1) % 6 + 1}"
link_2_annotator = f"user_{(i+2) % 6 + 1}"
```

should be changed to

```python
link_1_idx = (i+1) % self.num_annotators + 1
link_2_idx = (i+2) % self.num_annotators + 1
link_1_annotator = f"user_{link_1_idx}"
link_2_annotator = f"user_{link_2_idx}"
```

**Comment by MiniEggz** [comment]
Thanks for catching that, had a look through the rest of the code and this seems to be the only place we left 6 hard-coded - added a fix for this on main.
